
version: '2'
services:
    vizzuality-coding-challenge-writer:
      build: './writer'
      container_name: "vizzuality-coding-challenge-writer"
      environment:
          - FLASK_APP=app.py
          - MONGODB_URI=mongodb://mongodb:27017
      ports:
          - 5000:5000
      links:
          - mongodb
      depends_on:
          - mongodb
    vizzuality-coding-challenge-reader:
      build: './writer'
      container_name: "vizzuality-coding-challenge-reader"
      environment:
          - NODE_ENV=development
          - MONGODB_URI=mongodb://mongodb:27017
      ports:
          - 3000:3000
      links:
          - mongodb
      depends_on:
          - mongodb
    vizzuality-coding-challenge-mongodb:
        image: mongo:latest
        container_name: "vizzuality-coding-challenge-mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
